"""Initial schema

Revision ID: d487f46cbd45
Revises: 
Create Date: 2026-08-30 18:51:15.908075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'd487f46cbd45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(length=100), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=True),
    sa.Column('center_lon', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcels_parcel_id'), 'parcels', ['parcel_id'], unique=True)
    
    op.create_table('buildings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.String(length=100), nullable=False),
    sa.Column('footprint', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('height_meters', sa.Float(), nullable=True),
    sa.Column('floor_count', sa.Integer(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lon', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_building_id'), 'buildings', ['building_id'], unique=False)
    
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('parcel_id', sa.String(length=100), nullable=True),
    sa.Column('building_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=True),
    sa.Column('progress_step', sa.String(length=200), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_building_id'), 'jobs', ['building_id'], unique=False)
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_jobs_parcel_id'), 'jobs', ['parcel_id'], unique=False)
    
    op.create_table('units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.String(length=100), nullable=False),
    sa.Column('ulpin', sa.String(length=200), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('floor_height_m', sa.Float(), nullable=True),
    sa.Column('polygon_2d', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lon', sa.Float(), nullable=True),
    sa.Column('area_sqft', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_ulpin'), 'units', ['ulpin'], unique=True)
    op.create_index(op.f('ix_units_unit_id'), 'units', ['unit_id'], unique=False)
    
    op.create_table('validation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('overlaps_detected', sa.Integer(), nullable=True),
    sa.Column('out_of_bounds', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('validation_report', sa.JSON(), nullable=True),
    sa.Column('checked_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
